### ISSUE TITLE
cmd builtin commands can be renamed which breaks code

### ISSUE THREAD

**Issue by EmilySeville7cfg** [RechInformatica/rech-editor-batch#17] opened 2022-11-25 13:54 UTC
For instance I can rename `set` command to non-space only string: `set` -> `blablabla`.

**Comment by gustavosimon** [comment] 2022-11-30 19:48
Hello @EmilySeville7cfg! Thanks for opening this issue!

Could you take more information for us about this issue?
I don't know if I understood the main problem.

**Comment by EmilySeville7cfg** [comment] 2022-12-01 03:56
@gustavosimon, suppose we have the following code snippet:

```cmd
set variable=value
rem some other code
set another_variable=another_value

```

Now I can rename `set` to `bla` and obtain:

```cmd
set variable=value
rem some other code
bla another_variable=another_value
```

Renaming is unpredictable for cmd internal commands: it renames internal command in some places and not in others. Program can accidentally break or start working strangely if there is `bla` executable in the `%PATH%`.

**Comment by gustavosimon** [comment] 2022-12-05 15:57
Hello @EmilySeville7cfg ! I tried to reproduce your issue but I'm still confusing.

Taking your example, what should happen if you rename `set` to `bla`? 
Do you expect that the code would be like this? If yes, did you tried this with an updated VSCode version? 

```cmd
bla variable=value
rem some other code
bla another_variable=another_value
```

Could you add in this issue your step by step? (or like a gif)

**Comment by gustavosimon** [comment] 2022-12-05 17:20
I think that I got that error in my VSCode. 
I'm going to investigate.

**Comment by EmilySeville7cfg** [comment] 2022-12-06 02:02
> Taking your example, what should happen if you rename set to bla?

Basically nothing should happen as it's a builtin for cmd and must not be renamed.

**Comment by gustavosimon** [comment] 2023-05-06 00:59
Hello @EmilySeville7cfg ! Hope u are well.

Have this issue fixed in version 0.0.22? Or it's still a bug for you?

**Comment by EmilySeville7cfg** [comment] 2023-05-06 01:11
@gustavosimon, given the following code:

```cmd
set variable=value
rem some other code
set another_variable=another_value
```

renaming `set` -> `bla` results in:

```cmd
bla variable=value
rem some other code
bla another_variable=another_value
```

I think it's better to deny renaming for internal cmd commands.

**Comment by gustavosimon** [comment] 2023-05-06 15:29
Hello @EmilySeville7cfg !

I think we have to split the behaviors. My question was about the original issue. Was it fixed?
Because, in this case we can close this issue.

The behavior that you just checked out, I think that is a enhancement issue. I don't know if we should deny renaming reserved cmd commands, I have to thing more about it.

If we close this issue we can open a new issue with your suggestion.

**Closed** 2023-05-06 16:00 UTC
Labels: bug
